---
title: "open2"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferGraph)
```
<br>

### Argument pdf
```{r}
open2(pdf = TRUE, pdf.name = "safer1")
```
<br>

### Argument pdf.path
```{r}
open2(pdf.path = ".")
```
<br>

### Argument pdf.name
```{r}
open2(pdf.name = "safer-r")
open2(pdf.name = "graph-safer")
```
<br>

### Argument width
```{r}
open2(width = 10, pdf.name = "safer3")
open2(width = 7, pdf.name = "safer4")
```
<br>

### Argument height
```{r}
open2(height = 8, pdf.name = "safer5")
open2(height = 7, pdf.name = "safer6")
```
<br>

### Argument paper
```{r}
open2(paper = "a4", pdf.name = "safer7")
open2(paper = "special", pdf.name = "safer8")
```
<br>

### Argument pdf.overwrite
```{r}
open2(pdf.overwrite = TRUE)
```
<br>

### Argument rescale
```{r}
open2(rescale = "fit", pdf.name = "safer9")
open2(rescale = "fixed", pdf.name = "safer10")
```
<br>

### Argument remove.read.only
```{r}
open2(remove.read.only = FALSE, pdf.name = "safer11")
open2(remove.read.only = TRUE, pdf.name = "safer12")
```
<br>

### Argument return.output
```{r}
open2(return.output = TRUE, pdf.name = "safer13")
open2(return.output = FALSE, pdf.name = "safer14")
```
<br>

### Argument pdf
```{r}
open2(pdf = TRUE, pdf.path = ".", pdf.name = "name1", width = 10, height = 8, paper = "a4", pdf.overwrite = TRUE, rescale = "fit", remove.read.only = FALSE, return.output = TRUE)

open2(pdf = TRUE, pdf.path = ".", pdf.name = "graph1", width = 7, height = 7, paper = "special", pdf.overwrite = FALSE, rescale = "fixed", remove.read.only = TRUE, return.output = FALSE)
```
<br>

### Argument safer_check
```{r}
open2(safer_check = TRUE, pdf.name = "safer15")
```
<br>

### All the arguments
```{r}
open2(
  pdf = TRUE, 
  pdf.path = ".", 
  pdf.name = "name1", 
  width = 10, 
  height = 8, 
  paper = "a4", 
  pdf.overwrite = TRUE, 
  rescale = "fit", 
  remove.read.only = TRUE, 
  return.output = FALSE,
  safer_check = TRUE
)
```
<br>