---
title: "scale2"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferGraph)
```
<br>

### Argument n, lim
```{r}
scale2(n = 5, lim = c(0, 100))
```
<br>

### Argument kind
```{r}
scale2(n = 9, lim = c(2, 3.101), kind = "approx")
```
<br>

### Argument safer_check 
```{r}
scale2(n = 9, lim = c(2, 3.101), safer_check = TRUE)
```
<br>

### Strict number of main ticks
```{r}
ymin = 2 ; 
ymax = 3.101 ; 
n = 5 ; 
scale <- scale2(n = n, lim = c(ymin, ymax), kind = "strict") ; 
scale ; 
par(yaxt = "n", yaxs = "i", las = 1) ; 
plot(ymin:ymax, ymin:ymax, xlim = base::range(scale, ymin, ymax)[order(c(ymin, ymax))], ylim = base::range(scale, ymin, ymax)[order(c(ymin, ymax))], xlab = "DEFAULT SCALE", ylab = "NEW SCALE") ; 
par(yaxt = "s") ; 
axis(side = 2, at = scale)
```
<br>


### strict "clean" number of main ticks
```{r}
ymin = 2 ; 
ymax = 3.101 ; 
n = 5 ; 
scale <- scale2(n = n, lim = c(ymin, ymax), kind = "strict.cl") ; 
scale ; 
par(yaxt = "n", yaxs = "i", las = 1) ; 
plot(ymin:ymax, ymin:ymax, xlim = base::range(scale, ymin, ymax)[order(c(ymin, ymax))], ylim = base::range(scale, ymin, ymax)[order(c(ymin, ymax))], xlab = "DEFAULT SCALE", ylab = "NEW SCALE") ; 
par(yaxt = "s") ; 
axis(side = 2, at = scale)
```
<br>


### approximate number of main ticks, scale inversion
```{r}
ymin = 3.101 ; 
ymax = 2 ; 
n = 5 ; 
scale <- scale2(n = n, lim = c(ymin, ymax), kind = "approx") ; 
scale ; 
par(yaxt = "n", yaxs = "i", las = 1) ; 
plot(ymin:ymax, ymin:ymax, xlim = base::range(scale, ymin, ymax)[order(c(ymin, ymax))], ylim = base::range(scale, ymin, ymax)[order(c(ymin, ymax))], xlab = "DEFAULT SCALE", ylab = "NEW SCALE") ; 
par(yaxt = "s") ; 
axis(side = 2, at = scale)
```
<br>

