---
title: "width"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferGraph)
```
<br>

### Mandatory Arguments categ.nb, inch.left.space and inch.right.space
```{r}
width(categ.nb = 10, inch.left.space = 1, inch.right.space = 1,)
```
<br>

### Argument inches.per.categ.nb
```{r}
width(categ.nb = 10, inches.per.categ.nb = 0.2, inch.left.space = 1, inch.right.space = 1,)
```
<br>

### Argument ini.window.width
```{r}
width(categ.nb = 10, inch.left.space = 1, inch.right.space = 1, ini.window.width = 7)
```
<br>

### Argument boundarie.space
```{r}
width(categ.nb = 10, inch.left.space = 1, inch.right.space = 1, boundarie.space = 0.5)
```
<br>

### Argument safer_check
```{r}
width(categ.nb = 10, inch.left.space = 1, inch.right.space = 1, safer_check = TRUE)
```
<br>

### All the arguments
```{r}
width(
  categ.nb = 10, 
  inches.per.categ.nb = 0.2, 
  ini.window.width = 7, 
  inch.left.space = 1, 
  inch.right.space = 1, 
  boundarie.space = 0.5,
  safer_check = TRUE
)
```
